### ISSUE TITLE
Reference Video or Documents

### ISSUE THREAD

**Issue by coolpalani** [david-hill/rhosp12#1]
Hello,

Can I get any reference Video or documents for execution flow of your file to install OpenStack Director and Overcloud

**Comment by coolpalani** [comment]
Hello,

Can I get any updates

**Comment by david-hill** [comment]
What are you trying to do exactly?

**Comment by coolpalani** [comment]
Hello David,

I'm trying to install RedHat OpenStack in simple way through automation. I though you're simplifying this task via Ansible. So that's what I asked reference documents for go through and do it

**Comment by david-hill** [comment]
Well I'm using shell scripts instead of ansible ... I know bash better ;)

**Comment by david-hill** [comment]
If you want to look at the shell scripts, it's located in https://github.com/david-hill/cloud/

**Comment by coolpalani** [comment]
Thank you very much for your response.
I am little familiar with Ansible and complete the RedHat OpenStack Platform 11 installations :)
